version: '2.4'

services:
  nginx:
    image: nginx:1.19.8-alpine
    ports:
      - "8000:80"
    volumes:
      - .:/mnt
      - ./conf/nginx/local.conf:/etc/nginx/conf.d/default.conf
    links:
      - "django:django.localhost"

  mysql:
    extends:
      file: docker-compose.common.yml
      service: mysql
    volumes:
      - ./var/mysql:/var/lib/mysql
      - .:/mnt

  django:
    extends:
      file: docker-compose.common.yml
      service: django
    restart: always
    links:
      - "mysql:mysql"
    depends_on:
      mysql:
        condition: service_healthy
