version: '2.4'

services:
  mysql:
    extends:
      file: docker-compose.common.yml
      service: mysql

  django:
    image: ${CONTAINER_TEST_IMAGE}
    extends:
      file: docker-compose.common.yml
      service: django
    command: python manage.py test
    links:
      - "mysql:mysql"
    depends_on:
      mysql:
        condition: service_healthy
