# Generated by Django 3.2.13 on 2022-06-14 11:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apply', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='agrodigital',
            name='release_year',
            field=models.CharField(max_length=255, verbose_name='Год реализации кейса'),
        ),
        migrations.AlterField(
            model_name='agrolaunch',
            name='release_year',
            field=models.CharField(max_length=255, verbose_name='Год запуска кейса'),
        ),
        migrations.AlterField(
            model_name='agromachinery',
            name='release_year',
            field=models.CharField(max_length=255, verbose_name='Год реализации кейса'),
        ),
        migrations.AlterField(
            model_name='futurefood',
            name='release_year',
            field=models.CharField(max_length=255, verbose_name='Год реализации кейса'),
        ),
        migrations.AlterField(
            model_name='madeinrussia',
            name='release_year',
            field=models.CharField(max_length=255, verbose_name='Год запуска кейса'),
        ),
    ]
