# Generated by Django 3.2.13 on 2022-06-15 05:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apply', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='agrodigital',
            name='case_name',
            field=models.CharField(default='-', max_length=255, verbose_name='Название кейса'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='agromachinery',
            name='case_name',
            field=models.CharField(default='-', max_length=255, verbose_name='Название кейса'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='futurefood',
            name='case_name',
            field=models.CharField(default='-', max_length=255, verbose_name='Название кейса'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='madeinrussia',
            name='case_name',
            field=models.CharField(default='-', max_length=255, verbose_name='Название кейса'),
            preserve_default=False,
        ),
    ]
