# Generated by Django 3.2.13 on 2022-06-15 05:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('apply', '0002_auto_20220614_1405'),
        ('apply', '0002_auto_20220615_0802'),
    ]

    operations = [
    ]
