# Generated by Django 3.2.13 on 2022-10-20 09:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apply', '0006_auto_20220616_0730'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='agrodigital',
            options={'verbose_name': 'заявку', 'verbose_name_plural': 'Цифровизация года'},
        ),
        migrations.AlterModelOptions(
            name='agrohero',
            options={'verbose_name': 'заявку', 'verbose_name_plural': 'Лидер года'},
        ),
        migrations.AlterModelOptions(
            name='agroidea',
            options={'verbose_name': 'заявку', 'verbose_name_plural': 'Идея года'},
        ),
        migrations.AlterModelOptions(
            name='agrolaunch',
            options={'verbose_name': 'заявку', 'verbose_name_plural': 'Запуск года'},
        ),
        migrations.AlterModelOptions(
            name='callme',
            options={'verbose_name': 'заявку', 'verbose_name_plural': '0 - Заявки из попапа'},
        ),
        migrations.AlterModelOptions(
            name='firststep',
            options={'verbose_name': 'заявку', 'verbose_name_plural': '1 - Заявки с первого шага'},
        ),
        migrations.AlterModelOptions(
            name='futurefood',
            options={'verbose_name': 'заявку', 'verbose_name_plural': 'Еда будущего'},
        ),
        migrations.AlterModelOptions(
            name='madeinrussia',
            options={'verbose_name': 'заявку', 'verbose_name_plural': 'Своя технология'},
        ),
        migrations.AlterField(
            model_name='agrodigital',
            name='nomination',
            field=models.CharField(choices=[('agro_machinery', 'Agro Machinery'), ('agro_digital', 'Цифровизация года'), ('future_food', 'Еда будущего'), ('made_in_russia', 'Своя технология'), ('agro_hero', 'Лидер года'), ('agro_launch', 'Запуск года'), ('agro_idea', 'Идея года')], max_length=14, verbose_name='Номинация'),
        ),
        migrations.AlterField(
            model_name='agrohero',
            name='nomination',
            field=models.CharField(choices=[('agro_machinery', 'Agro Machinery'), ('agro_digital', 'Цифровизация года'), ('future_food', 'Еда будущего'), ('made_in_russia', 'Своя технология'), ('agro_hero', 'Лидер года'), ('agro_launch', 'Запуск года'), ('agro_idea', 'Идея года')], max_length=14, verbose_name='Номинация'),
        ),
        migrations.AlterField(
            model_name='agroidea',
            name='nomination',
            field=models.CharField(choices=[('agro_machinery', 'Agro Machinery'), ('agro_digital', 'Цифровизация года'), ('future_food', 'Еда будущего'), ('made_in_russia', 'Своя технология'), ('agro_hero', 'Лидер года'), ('agro_launch', 'Запуск года'), ('agro_idea', 'Идея года')], max_length=14, verbose_name='Номинация'),
        ),
        migrations.AlterField(
            model_name='agrolaunch',
            name='nomination',
            field=models.CharField(choices=[('agro_machinery', 'Agro Machinery'), ('agro_digital', 'Цифровизация года'), ('future_food', 'Еда будущего'), ('made_in_russia', 'Своя технология'), ('agro_hero', 'Лидер года'), ('agro_launch', 'Запуск года'), ('agro_idea', 'Идея года')], max_length=14, verbose_name='Номинация'),
        ),
        migrations.AlterField(
            model_name='agromachinery',
            name='nomination',
            field=models.CharField(choices=[('agro_machinery', 'Agro Machinery'), ('agro_digital', 'Цифровизация года'), ('future_food', 'Еда будущего'), ('made_in_russia', 'Своя технология'), ('agro_hero', 'Лидер года'), ('agro_launch', 'Запуск года'), ('agro_idea', 'Идея года')], max_length=14, verbose_name='Номинация'),
        ),
        migrations.AlterField(
            model_name='futurefood',
            name='nomination',
            field=models.CharField(choices=[('agro_machinery', 'Agro Machinery'), ('agro_digital', 'Цифровизация года'), ('future_food', 'Еда будущего'), ('made_in_russia', 'Своя технология'), ('agro_hero', 'Лидер года'), ('agro_launch', 'Запуск года'), ('agro_idea', 'Идея года')], max_length=14, verbose_name='Номинация'),
        ),
        migrations.AlterField(
            model_name='madeinrussia',
            name='nomination',
            field=models.CharField(choices=[('agro_machinery', 'Agro Machinery'), ('agro_digital', 'Цифровизация года'), ('future_food', 'Еда будущего'), ('made_in_russia', 'Своя технология'), ('agro_hero', 'Лидер года'), ('agro_launch', 'Запуск года'), ('agro_idea', 'Идея года')], max_length=14, verbose_name='Номинация'),
        ),
    ]
