# Generated by Django 3.2.13 on 2022-06-13 14:32

from django.db import migrations, models
import easy_thumbnails.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AwardCeremony',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('place', models.TextField(verbose_name='Место')),
                ('address', models.TextField(blank=True, default='', verbose_name='Адресс')),
                ('date', models.DateField(verbose_name='Дата')),
                ('about_date', models.TextField(blank=True, default='', verbose_name='Описание даты')),
            ],
            options={
                'verbose_name': 'Запись',
                'verbose_name_plural': 'Церемония вручения',
            },
        ),
        migrations.CreateModel(
            name='Cover',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('stage', models.CharField(choices=[('1', 'Прием заявок на премию'), ('2', 'Отбор номинантов в Short List'), ('3', 'Публикация Short List'), ('4', 'День проведения премии')], max_length=1, verbose_name='Текущий этап')),
                ('place', models.TextField(blank=True, default='', verbose_name='Место проведения')),
                ('time', models.TextField(blank=True, default='', verbose_name='Время проведения')),
            ],
            options={
                'verbose_name': 'Обложку',
                'verbose_name_plural': 'Обложка',
            },
        ),
        migrations.CreateModel(
            name='Document',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(choices=[('regulation_on_participation', 'Положение об участии'), ('privacy_policy', 'Политика конфиденциальности')], max_length=27, unique=True, verbose_name='Название файла')),
                ('file', models.FileField(upload_to='document', verbose_name='Файл')),
            ],
            options={
                'verbose_name': 'Документ',
                'verbose_name_plural': 'Дополнительные файлы',
            },
        ),
        migrations.CreateModel(
            name='Jury',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Имя')),
                ('surname', models.CharField(max_length=255, verbose_name='Фамилия')),
                ('company', models.CharField(blank=True, default='', max_length=255, verbose_name='Компания')),
                ('role', models.CharField(blank=True, default='', max_length=255, verbose_name='Должность')),
                ('photo', easy_thumbnails.fields.ThumbnailerField(upload_to='jury', verbose_name='Фото')),
                ('order', models.PositiveIntegerField()),
            ],
            options={
                'verbose_name': 'Жюри',
                'verbose_name_plural': 'Жюри',
                'ordering': ('order',),
            },
        ),
        migrations.CreateModel(
            name='Nominee',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nomination', models.CharField(choices=[('agro_machinery', 'Agro Machinery'), ('agro_digital', 'Agro Digital'), ('future_food', 'Future Food'), ('made_in_russia', 'Made in Russia'), ('agro_hero', 'Agro Hero'), ('agro_launch', 'Agro Launch'), ('agro_idea', 'Agro Idea')], max_length=14, verbose_name='Номинация')),
                ('project_name', models.CharField(max_length=255, verbose_name='Название проекта')),
                ('founder', models.CharField(max_length=255, verbose_name='Создатель проекта')),
                ('description', models.TextField(verbose_name='Описание')),
                ('photo', easy_thumbnails.fields.ThumbnailerField(blank=True, null=True, upload_to='founder', verbose_name='Фото')),
                ('is_winner', models.BooleanField(blank=True, default=False, verbose_name='Победитель')),
            ],
            options={
                'verbose_name': 'Номинант',
                'verbose_name_plural': 'Номинанты',
            },
        ),
        migrations.CreateModel(
            name='Partner',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Название')),
                ('logo', easy_thumbnails.fields.ThumbnailerField(upload_to='partner', verbose_name='Логотип')),
                ('url', models.URLField(blank=True, default='', verbose_name='url')),
                ('order', models.PositiveIntegerField()),
            ],
            options={
                'verbose_name': 'Партнёр',
                'verbose_name_plural': 'Партнёры',
                'ordering': ('order',),
            },
        ),
        migrations.CreateModel(
            name='Stage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('stage', models.CharField(choices=[('1', 'Прием заявок на премию'), ('2', 'Отбор номинантов в Short List'), ('3', 'Публикация Short List'), ('4', 'День проведения премии')], max_length=1, unique=True, verbose_name='Текущий этап')),
                ('start_date', models.DateField(blank=True, null=True, verbose_name='Дата начала')),
                ('stop_date', models.DateField(verbose_name='Дата окончания')),
            ],
            options={
                'verbose_name': 'Этап',
                'verbose_name_plural': 'Этапы проведения',
            },
        ),
    ]
