# Generated by Django 3.2.13 on 2022-06-28 14:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='nominee',
            options={'ordering': ('order',), 'verbose_name': 'Номинант', 'verbose_name_plural': 'Номинанты'},
        ),
        migrations.AddField(
            model_name='nominee',
            name='order',
            field=models.PositiveIntegerField(default=0),
            preserve_default=False,
        ),
    ]
