# Generated by Django 3.2.13 on 2022-10-20 06:33

from django.db import migrations, models
import tinymce.models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_auto_20220628_1730'),
    ]

    operations = [
        migrations.CreateModel(
            name='FAQ',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question', models.CharField(max_length=255, verbose_name='Вопрос')),
                ('answer', tinymce.models.HTMLField(verbose_name='Ответ')),
                ('order', models.PositiveIntegerField()),
            ],
            options={
                'verbose_name': 'Вопрос',
                'verbose_name_plural': 'FAQ',
                'ordering': ('order',),
            },
        ),
    ]
