# Generated by Django 3.2.13 on 2022-10-20 09:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0003_faq'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cover',
            name='stage',
            field=models.CharField(choices=[('1', 'Прием заявок на премию'), ('2', 'Отбор номинантов в Short List'), ('3', 'Публикация Short List'), ('4', 'Питчи шорт-листа и проведение церемонии награждения')], max_length=1, verbose_name='Текущий этап'),
        ),
        migrations.AlterField(
            model_name='nominee',
            name='nomination',
            field=models.CharField(choices=[('agro_machinery', 'Agro Machinery'), ('agro_digital', 'Цифровизация года'), ('future_food', 'Еда будущего'), ('made_in_russia', 'Своя технология'), ('agro_hero', 'Лидер года'), ('agro_launch', 'Запуск года'), ('agro_idea', 'Идея года')], max_length=14, verbose_name='Номинация'),
        ),
        migrations.AlterField(
            model_name='stage',
            name='stage',
            field=models.CharField(choices=[('1', 'Прием заявок на премию'), ('2', 'Отбор номинантов в Short List'), ('3', 'Публикация Short List'), ('4', 'Питчи шорт-листа и проведение церемонии награждения')], max_length=1, unique=True, verbose_name='Текущий этап'),
        ),
    ]
